site_name: Nano HTTP Request Component
site_url: https://NanoComponents.github.io/http/
docs_dir: docs

theme:
  name: readthedocs
  logo: images/logo.png
  favicon: images/favicon.ico

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - API Reference: api-reference.md
  - Architecture Overview: architecture.md
  - Changelog: changelog.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

