site_name: Nano HTTP Request Component
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api-reference.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Changelog: changelog.md
